[package]
name = "sequenceprofiler"
version = "0.7.0"
edition = "2021"
readme = "README.md"
license = "MIT"
authors = ["Gaurav Sablok"]
description = "sequence profiling crate"
homepage = "https://codeberg.org/gsablok/sequenceprofiler"
repository = "https://codeberg.org/gsablok/sequenceprofiler"
keywords = ["bioinformatics","genomics"]

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
derive = "1.0.0"
features = "0.10.0"
figlet-rs = "0.1.5"
rayon = "1.11.0"
